## 演習：モデル作成

- データの読み込み
    - 欠損値の確認
    - 文字列データの有無の確認
- 特定の列の削除
    - BILL_AMT2	
    - BILL_AMT3
    - BILL_AMT4
    - BILL_AMT5
    - BILL_AMT6
- データを検証データと訓練データへ切り分け：(テストデータを30%)
- 学習：決定木（分類）
- モデルの保存　→ demo_model.pkl
- モデルの読み込み
- 推論(分類結果＆確率)
    
`default payment next month` ←  教師データ t

In [21]:
%matplotlib inline
import numpy as np
import pandas as pd

In [23]:
df = pd.read_csv('default.csv')
df.head(2)

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   

   PAY_5             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0     -2             ...                      0          0          0   
1      0             ...                   3272       3455       3261   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         0       689         0         0         0         0   
1         0      1000      1000      1000         0      2000   

   default payment next month  
0                           1  
1                           1  

[2 rows x 24 columns]

In [25]:
# 欠損値の有無の確認
df.isnull().sum()

LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [31]:
df.select_dtypes(include='object')[:3]

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [32]:
df.head(2)

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   

   PAY_5             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0     -2             ...                      0          0          0   
1      0             ...                   3272       3455       3261   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         0       689         0         0         0         0   
1         0      1000      1000      1000         0      2000   

   default payment next month  
0                           1  
1                           1  

[2 rows x 24 columns]

In [33]:
# df.drop(labels=['BILL_AMT2','BILL_AMT2','BILL_AMT2','BILL_AMT2'])

In [35]:
for i in range(2,7):
    df.drop(labels=['BILL_AMT{}'.format(i)], inplace=True, axis=1)

In [39]:
print(df.columns)

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'PAY_AMT1', 'PAY_AMT2',
       'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')


In [42]:
df.shape

(30000, 19)

In [43]:
df.head(2)

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   

   PAY_5  PAY_6  BILL_AMT1  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  \
0     -2     -2       3913         0       689         0         0         0   
1      0      2       2682         0      1000      1000      1000         0   

   PAY_AMT6  default payment next month  
0         0                           1  
1      2000                           1

教師データtの切り分け

In [49]:
t = df.iloc[:, -1].values
x = df.iloc[:, :-1].values

In [48]:
type(x)

numpy.ndarray

訓練と検証データへの分割

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
x_train, x_test, t_train, t_test = train_test_split(x, t, test_size=0.3, random_state=1)

In [52]:
x_train.shape

(21000, 18)

In [53]:
t_train.shape

(21000,)

In [54]:
from sklearn.tree import DecisionTreeClassifier

In [64]:
model = DecisionTreeClassifier(random_state=0, max_depth=7)

In [65]:
# 学習の実行
model.fit(x_train, t_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [66]:
# モデルの検証
print(model.score(x_train, t_train))
print(model.score(x_test, t_test))

0.8323333333333334
0.8172222222222222


モデルの保存

In [67]:
from sklearn.externals import joblib

In [68]:
joblib.dump(model, 'demo_model.pkl')

['demo_model.pkl']

In [69]:
loaded_model = joblib.load('demo_model.pkl')

In [72]:
x_new = x[0]
x_new

array([20000,     2,     2,     1,    24,     2,     2,    -1,    -1,
          -2,    -2,  3913,     0,   689,     0,     0,     0,     0])

In [76]:
y = loaded_model.predict([x_new])
y

array([0])

In [77]:
y_proba = loaded_model.predict_proba([x_new])
y_proba

array([[0.88235294, 0.11764706]])

In [79]:
y[0]

0

In [83]:
y_proba[0][y[0]]

0.8823529411764706

## 演習：result.htmlを表示してください

- URL名は result
- view関数名も result
- html名も result.html
    -  審査結果
- input_formで入力が完了した時、result のページにリダイレクトするように設定